services:
  postgres_db:
    image: postgres:15
    container_name: food_ordering_db
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - food_postgres_data:/var/lib/postgresql/data
    networks:
      - food_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer:latest
    container_name: food_ordering_adminer
    restart: unless-stopped
    ports:
      - "5051:8080"
    depends_on:
      postgres_db:
        condition: service_healthy
    networks:
      - food_network

volumes:
  food_postgres_data:

networks:
  food_network: