CREATE TYPE "role_enum" AS ENUM (
  'STUDENT',
  'VENDOR',
  'ADMIN'
);

CREATE TYPE "vendor_status_enum" AS ENUM (
  'PENDING',
  'APPROVED',
  'BLOCKED'
);

CREATE TYPE "user_status_enum" AS ENUM (
  'ACTIVE',
  'INACTIVE',
  'BLOCKED'
);

CREATE TYPE "order_status_enum" AS ENUM (
  'PENDING',
  'PREPARING',
  'DELIVERING',
  'ARRIVED',
  'COMPLETED',
  'CANCELLED'
);

CREATE TYPE "payment_status_enum" AS ENUM (
  'UNPAID',
  'PENDING',
  'PAID',
  'FAILED'
);

CREATE TYPE "payment_method_enum" AS ENUM (
  'COD',
  'TRANSFER'
);

CREATE TABLE "users" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "phone" varchar UNIQUE NOT NULL,
  "password" varchar NOT NULL,
  "role" role_enum NOT NULL DEFAULT 'STUDENT',
  "status" user_status_enum NOT NULL DEFAULT 'ACTIVE',
  "shop_name" varchar,
  "vendor_status" vendor_status_enum,
  "bank_name" varchar,
  "bank_account_number" varchar,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "buildings" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE NOT NULL,
  "description" text,
  "is_active" boolean DEFAULT true
);

CREATE TABLE "categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vendor_id" uuid NOT NULL,
  "name" varchar NOT NULL,
  "is_deleted" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "foods" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "vendor_id" uuid NOT NULL,
  "category_id" int NOT NULL,
  "name" varchar NOT NULL,
  "description" text,
  "price" decimal NOT NULL,
  "image_url" varchar,
  "is_available" boolean DEFAULT true,
  "is_deleted" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "orders" (
  "id" uuid PRIMARY KEY DEFAULT (gen_random_uuid()),
  "student_id" uuid NOT NULL,
  "vendor_id" uuid NOT NULL,
  "building_id" int NOT NULL,
  "total_amount" decimal NOT NULL,
  "status" order_status_enum NOT NULL DEFAULT 'PENDING',
  "payment_method" payment_method_enum NOT NULL DEFAULT 'COD',
  "payment_status" payment_status_enum NOT NULL DEFAULT 'UNPAID',
  "bill_image_url" varchar,
  "note" text,
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "order_items" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" uuid NOT NULL,
  "food_id" int,
  "food_name" varchar NOT NULL,
  "price" decimal NOT NULL,
  "quantity" int NOT NULL DEFAULT 1
);

CREATE INDEX ON "users" ("role");

CREATE INDEX ON "users" ("status");

CREATE UNIQUE INDEX ON "categories" ("vendor_id", "name");

CREATE INDEX ON "categories" ("vendor_id");

CREATE INDEX ON "foods" ("vendor_id");

CREATE INDEX ON "foods" ("category_id");

CREATE INDEX ON "foods" ("vendor_id", "is_available");

CREATE INDEX ON "foods" ("vendor_id", "is_deleted");

CREATE INDEX ON "orders" ("student_id");

CREATE INDEX ON "orders" ("vendor_id");

CREATE INDEX ON "orders" ("status");

CREATE INDEX ON "order_items" ("order_id");

COMMENT ON COLUMN "foods"."price" IS 'price > 0 (validate backend)';

COMMENT ON COLUMN "foods"."image_url" IS 'Link image Cloudinary';

COMMENT ON COLUMN "foods"."is_available" IS 'Bật/tắt món (Còn hàng/Hết hàng)';

COMMENT ON COLUMN "foods"."is_deleted" IS 'Soft Delete: Ẩn món không xóa data gốc';

COMMENT ON COLUMN "orders"."note" IS 'Ghi chú của sinh viên (VD: ít cay)';

COMMENT ON COLUMN "order_items"."food_name" IS 'Lưu cứng tên món lúc đặt, tránh việc quán đổi tên sau này';

COMMENT ON COLUMN "order_items"."price" IS 'Lưu cứng giá món lúc đặt, tránh việc quán tăng giá làm sai bill';

ALTER TABLE "categories" ADD FOREIGN KEY ("vendor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "foods" ADD FOREIGN KEY ("vendor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "foods" ADD FOREIGN KEY ("category_id") REFERENCES "categories" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("student_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("vendor_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "orders" ADD FOREIGN KEY ("building_id") REFERENCES "buildings" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("order_id") REFERENCES "orders" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "order_items" ADD FOREIGN KEY ("food_id") REFERENCES "foods" ("id") DEFERRABLE INITIALLY IMMEDIATE;
